<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'd' => 
  array (
    'img' => 
    array (
      0 => '../storage/image/title-main logo.jpg',
      1 => '../storage/image/title-banner-choisbutcher-400x225.jpg',
      2 => '../storage/image/title-Untitled design (5).png',
      3 => '../storage/image/title-banner-studysa-400x225.jpg',
      4 => '../storage/image/title-Black Feminine Initial Flower.png',
      5 => '../storage/image/title-Barun_Inside-배너-001.jpg',
      6 => '../storage/image/title-KakaoTalk_20240529_113429846.png',
      7 => '../storage/image/title-adelaide (2200 x 1125 px) (1).png',
      8 => '../storage/image/title-게임-008.png',
      9 => '../storage/image/title-Raon.png',
      10 => '../storage/image/title-게임-009 (1).png',
      11 => '../storage/image/title-게임-010 (3).png',
    ),
    'link' => 
    array (
      0 => 'https://otherhome.org',
      1 => 'http://www.choisbutcher.com/',
      2 => 'https://ko.home4u.au/',
      3 => 'http://www.studysa.com.au/',
      4 => 'https://www.fresha.com/a/hair-blooming-adelaide-169-hutt-street-da3up5zi',
      5 => 'https://barunmeats.com.au/',
      6 => 'https://open.kakao.com/o/gDGHYWVe',
      7 => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_main',
      8 => 'https://maps.app.goo.gl/TWVXV4gtNnLiRhTf9',
      9 => 'https://maps.app.goo.gl/Y2oTRXHSLCEMwGg59',
      10 => 'https://www.handsonchirohealth.com.au/',
      11 => 'https://adelaideinside.com/bbs/board.php?bo_table=store&wr_id=77&sca=%EA%B8%B0%ED%83%80',
    ),
    'alt' => 
    array (
      0 => 'Otherhome',
      1 => '최가네 정육점',
      2 => 'home4u',
      3 => '스터디SA',
      4 => 'Hair Blooming',
      5 => '바른 정육점',
      6 => '투게더 마트',
      7 => '루씨네 공구',
      8 => 'Kane\\\'s Painting & Decorating Pty Ltd',
      9 => 'Raon Painting',
      10 => 'Hands on Chiropractic & Health - Chiropractic, Massage',
      11 => '쿠쿠 정수기',
    ),
    'target' => 
    array (
      0 => '_blank',
      1 => '_blank',
      2 => '_blank',
      3 => '_blank',
      4 => '_blank',
      5 => '_blank',
      6 => '_blank',
      7 => '_blank',
      8 => '_blank',
      9 => '_blank',
      10 => '_blank',
      11 => '_blank',
    ),
  ),
  'nav' => '1',
  'thumb_w' => '',
  'thumb_h' => '',
  'margin' => '',
  'padding' => '',
  'xl' => '2',
  'lg' => '4',
  'md' => '3',
  'sm' => '3',
  'xs' => '2',
);