<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'cache' => '',
  'bo_new' => '24',
  'new' => '',
  'rank' => '',
  'target' => '',
  'bo_name' => '',
  'thumb_w' => '',
  'thumb_h' => '',
  'thumb_d' => '',
  'xl' => '4',
  'lg' => '4',
  'md' => '3',
  'sm' => '3',
  'xs' => '2',
  'gr_list' => '',
  'bo_list' => 'countryside',
  'ca_list' => '',
  'mb_list' => '',
  'rows' => '4',
  'page' => '',
  'sort' => '',
  'term' => '',
  'dayterm' => '',
);