<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  0 => 
  array (
    'text' => '  News',
    'href' => '/bbs/group.php?gr_id=news',
    'icon' => 'fa-edge',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '비자뉴스',
        'href' => '/bbs/board.php?bo_table=visa',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '호주뉴스',
        'href' => '/bbs/board.php?bo_table=aus_news',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '한국뉴스',
        'href' => '/bbs/board.php?bo_table=kor_news',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '인사이드 뉴스',
        'href' => '/bbs/board.php?bo_table=notice',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '인사이드 매거진',
        'href' => '/bbs/board.php?bo_table=magazine',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  1 => 
  array (
    'text' => ' 커뮤니티',
    'href' => '/bbs/group.php?gr_id=community',
    'icon' => 'fa-info-circle',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '아무거나 말해요^^',
        'href' => '/bbs/board.php?bo_table=freeboard',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '무엇이든 물어보세요!',
        'href' => '/bbs/board.php?bo_table=QnA_2',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => 'FAQ',
        'href' => '/bbs/board.php?bo_table=QnA_1',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '워홀러 & 이민러',
        'href' => '/bbs/board.php?bo_table=workingholiday',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '이벤트 상품 리뷰',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=event_review',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => '피드백 받습니다!',
        'href' => '/bbs/board.php?bo_table= feedback',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  2 => 
  array (
    'text' => ' 일자리',
    'href' => '/bbs/board.php?bo_table=findjob',
    'icon' => 'fa-briefcase',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '구인',
        'href' => '/bbs/board.php?bo_table=findjob&amp;sca=구인',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '구직',
        'href' => '/bbs/board.php?bo_table=findjob&amp;sca=구직',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  3 => 
  array (
    'text' => '  인사이드 마켓',
    'href' => '/bbs/board.php?bo_table=used_item',
    'icon' => 'fa-shopping-cart',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '중고물품',
        'href' => '/bbs/board.php?bo_table=used_item',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  4 => 
  array (
    'text' => '  렌트 쉐어',
    'href' => '/bbs/board.php?bo_table=share',
    'icon' => 'fa-hotel',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '렌트',
        'href' => '/bbs/board.php?bo_table=share&amp;sca=렌트',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '쉐어',
        'href' => '/bbs/board.php?bo_table=share&amp;sca=쉐어',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  5 => 
  array (
    'text' => '꿀more팁',
    'href' => '/bbs/group.php?gr_id=shopping',
    'icon' => 'fa-flash',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '맛집 & 여행',
        'href' => '/bbs/group.php?gr_id=food',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '공연 & 축제',
        'href' => '/bbs/board.php?bo_table=performance',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '한인 업체 리스트',
        'href' => '/bbs/board.php?bo_table= store',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '업체게시판 및 안내',
        'href' => '/bbs/board.php?bo_table=event',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => 'Life TIP',
        'href' => '/bbs/board.php?bo_table=tips',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      5 => 
      array (
        'text' => 'Shopping TIP',
        'href' => '/bbs/board.php?bo_table=hotdeal',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      6 => 
      array (
        'text' => '쇼핑 카탈로그',
        'href' => '/bbs/board.php?bo_table=catalogue',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      7 => 
      array (
        'text' => '경제 칼럼',
        'href' => '/bbs/board.php?bo_table=property_column',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      8 => 
      array (
        'text' => '건강 칼럼',
        'href' => '/bbs/board.php?bo_table=medical',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
  6 => 
  array (
    'text' => '루씨네 공구',
    'href' => 'https://adelaideinside.com/bbs/group.php?gr_id=Lucy',
    'icon' => 'fa-users',
    'target' => '_self',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '공지사항',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_inform',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '루씨네 물건주문',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_main',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '타지역 픽업 신청',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_Pickup',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '루씨네 공구후기',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_review',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '루씨네 커뮤니티',
        'href' => '#',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
        's' => 
        array (
          0 => 
          array (
            'text' => '아름다운기부',
            'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_donation',
            'icon' => 'empty',
            'target' => '_self',
            'line' => '',
            'sp' => '',
            'limit' => '',
            'grade' => 0,
            'id' => 'link',
          ),
          1 => 
          array (
            'text' => '소모임',
            'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_communi',
            'icon' => 'empty',
            'target' => '_self',
            'line' => '',
            'sp' => '',
            'limit' => '',
            'grade' => 0,
            'id' => 'link',
          ),
        ),
      ),
      5 => 
      array (
        'text' => '중고/환전/나눔',
        'href' => 'https://adelaideinside.com/bbs/board.php?bo_table=Lucy_change',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
    ),
  ),
);