<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'seo' => '1',
  'seo_desc' => '남호주 애들레이드에 거주하는 사람들의 커뮤니티입니다.  한글로 된 호주 및 한국 뉴스를 공유하여 건강한 호주생활을 지원하며, 핫딜, 중고 물품 및 구인 구직 정보를 통해 알뜰한 호주생활을 도와드립니다. 커뮤니티 운영을 통한 교민들간 친목도모 및 정보공유로 건강하고 재미있는 애들레이드 생활을 지원합니다. ',
  'seo_keys' => 'adelaide inside, adelaideinside, 아들레이드, 애들레이드, 한인 커뮤니티, 애들레이드 핫딜, 애들레이드 쿠폰, 애들레이드 생활 정보, 애들레이드 약, 애들레이드 구인, 애들레이드 구직, 애들레이드 중고, 애들레이드 커뮤니티',
  'seo_img' => '../storage/image/seo-seo 사진.png',
  'logo_img' => '../storage/image/logo-Untitled design (7).png',
  'logo_text' => '애들레이드 인사이드',
  'stats' => '10',
  'noti' => '30',
  'font' => 'Nanum-Myeongjo-14px',
  'font_mo' => 'NEXON-Gothic-15px',
  'sub_pc' => '0',
  'layout' => 'ac',
  'size' => '1100',
  'bg_img' => '',
  'bg_pos' => 'center',
  'wing' => '0',
  'color' => 'Sunflower',
  'style' => '1',
  'line' => '1',
  'menu' => '1',
  'menu_w' => '0',
  'sub_w' => '150',
  'sticky' => '0',
  'index' => 'index-basic',
  'pwide' => '0',
  'pmax' => '1980',
  'ptitle' => '0',
  'scol' => '0',
  'sfile' => 'side-basic',
  'sloc' => 'right',
  'ftstyle' => 'box',
);