<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'thumb_w' => '400',
  'thumb_h' => '225',
  'thumb_d' => '56.25%',
  'xl' => '',
  'lg' => '',
  'md' => '3',
  'sm' => '',
  'xs' => '2',
  'no_img' => '../storage/image/no-image.png',
  'head_color' => '',
  'new' => '',
  'target' => '',
  'bo_admin' => '',
  'noti_mb' => '',
  'na_save_image' => '1',
  'na_crows' => '',
  'na_cob' => 'old',
  'na_lucky_point' => '',
  'na_lucky_dice' => '',
  'na_gcancel' => '',
  'na_gtimes' => '',
  'editor_mo' => '',
  'na_shingo' => '',
);