<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'cache' => '',
  'bo_new' => '24',
  'new' => '',
  'target' => '',
  'bo_name' => '',
  'c_color' => '',
  'speed' => '',
  'arrows' => '1',
  'dots' => '1',
  'round' => '5',
  'thumb_w' => '',
  'thumb_h' => '',
  'thumb_d' => '',
  'gr_list' => 'news',
  'bo_list' => '',
  'ca_list' => '',
  'mb_list' => '',
  'subject_line' => '1',
  'wcut' => '57',
  'profile' => '1',
  'rows' => '15',
  'page' => '',
  'sort' => '',
  'term' => '',
  'dayterm' => '',
);